### ISSUE TITLE
Document CIA to cross-section change in code doc.

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/transit#105]
Lots of changes:
See this merge: 1d8f656

Start with this:
- Filenames: cia.c --> crosssec.c
           cia.h --> crosssec.h
- Functions: readcia        --> readcs
           interpolatecia --> interpcs
           freemem_cia    --> freemem_cs
           ciaerr         --> cserr
- Struct and variables: th.ncia     --> th.ncross
                      th.ciafile  --> th.csfile
                      tr.ds.cia   --> tr.ds.cross
                      cia         --> cross
                      cia.cia     --> cross.cs
                      CLA_CIAFILE --> CLA_CSFILE
- Data Types: PREC_CIA --> PREC_CS
- Flags:      TRPI_CIA --> TRPI_CS

**Comment by rychallener** [comment]
Resolved by commit d69bf31971d1781f58cb3f550d8b3009bdd28c11
