### ISSUE TITLE
transmission mode doesn't write file

### ISSUE THREAD

**Issue by iancrossfield** [pcubillos/transit#128]
When running "transit_demo.cfg" in transit mode (not eclipse), the computed transmission spectrum is output to the screen but not saved to the filename specified in "outflux"

**Comment by rychallener** [comment]
I think this is actually an issue with having different variable names for the output of eclipse geometry vs. the output of transit geometry. The variable you are looking for is "outmod." I think this is unnecessary and unintuitive, and probably should be changed to a generic "output" variable.

**Comment by pcubillos** [comment]
Yes, I remember that we agreed a couple of months ago to rename it to ‘outpace’ (to be more specific than just output).
I’ll get it fixed later today.

Thanks for the reminder, sorry for the troubles.
Patricio.

**Comment by pcubillos** [comment]
I just propagated this update to the BART code.
