### ISSUE TITLE
Installation error under MacOSX

### ISSUE THREAD

**Issue by odemangeon** [pcubillos/transit#140]
I am trying to install BART on my machine (MacOS Sierra 10.12.6), but I get an early error during the installation of transit and more precisely the installation of pu.

When I run make, I've got several errors due to unknown option under OSX, and I had to modified the MakeFile:
Here is the modifications, I've made
ARCH_FLAG = -Wl,--whole-archive --> ARCH_FLAG = -Wl,-all_load
LIBM_FLAG = -Wl,--no-whole-archive -lm --> LIBM_FLAG =
NAME_FLAG = -Wl,-soname -Wl,libpu.so.1 --> NAME_FLAG = -Wl,-install_name,libpu.so.1

But I still get an error that I don't manage to fix:
> Apple LLVM version 9.0.0 (clang-900.0.39.2)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
>  "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -dylib -arch x86_64 -macosx_version_min 10.12.0 -o libpu.so.1 -all_load ./src/iomisc.o ./src/messagep.o ./src/numerical.o ./src/procopt.o ./src/sampling.o ./src/spline.o ./src/voigt.o ./src/xmalloc.o -install_name libpu.so.1 -lm -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
> Undefined symbols for architecture x86_64:
>   "_error", referenced from:
>       _xmalloc in xmalloc.o
>       _xcalloc in xmalloc.o
>       _xrealloc in xmalloc.o
>       _xstrdup in xmalloc.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [library] Error 1
> make: *** [make_pu] Error 2

Do you have an idea of what the problem/solution could be ?

**Comment by joeharr4** [comment]
BART currently only runs on Linux.  We have not yet undertaken getting it to run on other operating systems, but it should not be too difficult, if they support shared memory.  We're focusing on publishing the papers, first.  Please refer future user-support questions to the BART mailing lists, where the community can help you get set up and running.  Instructions are in the README on the main BART page.

Thanks,

--jh--

**Comment by natelust** [comment]
I have created a patch that allows transit to build and run on os x, and created a pull request. This is provided you have all the required dependencies and are running python 2.X. The working copy can be found at https://github.com/natelust/transit/tree/osx_fix, or waiting until (if?) it is merged to this repo.

**Comment by odemangeon** [comment]
Thanks for your help ! The compilation using https://github.com/natelust/transit/tree/osx_fix succeeded. (It first failed because I was not on the good branch).
