### ISSUE TITLE
Re-organize pu/ module.

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/transit#15]
Use the same folder usage for .c and .h as in the transit module.

**Comment by pcubillos** [comment]
The folder structure now is similar to the one in the transit/ folder.

**Comment by pcubillos** [comment]
Now, should we move the header files into the src/ folder as in transit/? or keep them in include/?

**Comment by natelust** [comment]
If you move these things around, you are going to need to change all the
info in the make files and the python setup.pi file for building the
transit wrapper
Nate

**Comment by aj-foster** [comment]
I'm a fan of putting headers in include/. Unless there are objections, I'll put this on my to-do list.

**Comment by aj-foster** [comment]
Apologies, I thought there were some rogue header files in src/. There aren't, so, I'll close this. If you decide later that you do want to move everything to src/, reopen and I'll do it.
