### ISSUE TITLE
Add the mass of molecules into the hitran.dat file

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/transit#16]
Need to fill the mass data for the HITRAN molecules file: pylineread/inputs/hitran.dat
Use the elemental isotopic mass from Lide et al (2008) book to calculate the species isotopic masses for the file.

**Comment by dzesmin** [comment]
Filled out all isotopes masses except NO+.

**Comment by pcubillos** [comment]
Calculated the mass of the NO+ (46) isotope as mass of 14_N + mass of 16_O - mass of electron.
