### ISSUE TITLE
Put pylineread in its own repo?

### ISSUE THREAD

**Issue by AndrewSDFoster** [pcubillos/transit#31]
I feel that pylineread should have its own repo that is also loaded as a submodule of BART. It is not required to run transit itself, just to create an input file for transit and is its own independent code that should be able to be easily replaceable. Giving it its own repository would make it clear that the user can replace it with the TLI file generator of their choice.

Thoughts?

**Comment by pcubillos** [comment]
The TLI data is necessary for almost every (scientifically interesting) Transit run.  I see only a limited number of cases where one would not be interested in including line-transition data.  It is true that a TLI file may be used by itself in a different project, but is is essential for Transit.  I would keep it in the same module as Transit.

**Comment by aj-foster** [comment]
Shall we close this for now, and revisit it later?

**Comment by joeharr4** [comment]
Pylineread is only useful as part of transit, so it should not be in its
own repo.

--jh--
