### ISSUE TITLE
Add system-requirements details

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/transit#4]
We need to properly document what are the Python, C, etc. system requirements.

**Comment by aj-foster** [comment]
So far we know:
- Python 2.7. _Do we care to test if it works in 2.6?_
- GCC/make. _I'll check version info._
- Certain things for shared memory. _I'll be more specific._
- MPI. _We can recommend the libraries we use, at least._

Anything to add, off the top of your head?

**Comment by joeharr4** [comment]
Don't care about py 2.6, do care about 3.x...

--jh--

**Comment by aj-foster** [comment]
I'm going to say that this is closed as of c6ecf7f. Will make a new issue for things related to Python 3.
