### ISSUE TITLE
Implement a dual writing output to a logfile and screen output

### ISSUE THREAD

**Issue by pcubillos** [pcubillos/transit#48]
Same idea as in the MC3 code.

**Comment by sdb05c** [comment]
I have one that works with the stdout for CEA (Fortra) in /home/esp01/studies/thermoplanet-sallyb/scripts/log.py. I know Joe commented that this can be done in bash as well but this is what I have already- written in Python.

**Comment by joeharr4** [comment]
It would seem to me that this is a problem that's often faced.  Unless
we're already using it, see if there is some standard way of doing this,
such as redefining "print" to write to two streams, or pipe to
/usr/bin/tee
The latter would make it unix-specific, though.

--jh--

**Comment by aj-foster** [comment]
Also, reference #30 in the process.

**Comment by aj-foster** [comment]
Furthermore, reference [this thread](https://physics.ucf.edu/pipermail/bart-devel/2015-July/000033.html).

**Comment by aj-foster** [comment]
Largely resolved by 861a753, though we might consider including how to do this in the Readme. Errors and other output are properly divided among stderr and stdout; redirection works as it should now.
