### ISSUE TITLE
Merge observable.c into slantpath.c?

### ISSUE THREAD

**Issue by rychallener** [pcubillos/transit#68]
observable.c just contains a driver function for the slantpath.c functions, a printing function, and a freemem function. These are all related to the modulation functions in slantpath.c, and it seems to me that they would be better off there to avoid confusion.

**Comment by pcubillos** [comment]
+1

**Comment by rychallener** [comment]
Resolved with 7f50752d180394b5f7432f6c4f9833c32040e90d
